### ISSUE TITLE
Some more info about the project

### ISSUE THREAD

**Issue by sdassh** [NootInc/WhateverRed#3]
Is this kext daily usable? Does everything work? Is hardware acceleration working? Could you put some more info in readme?

**Comment by ChefKissInc** [comment]
@sdassh No to all, it’s in active research/development, hence why all the debug commits.

**Comment by handicraftsman** [comment]
Some more questions:

Do you have any progress tracker?

When prebuilt binaries are going to become available? (I am asking for the condition, not ETA)

Are there going to be nightly builds, e.g. for testing?

**Comment by ChefKissInc** [comment]
@handicraftsman No progress tracker, live progress is done in the telegram group of @mvaisakh, see https://github.com/mvaisakh/Asus-X505ZA-Ryzen-Hackintosh/issues/1
A release will be made once all the AMD kexts succeed initialisation and startup, and macOS boots to the desktop on my Picasso test laptop
I don’t have CI set up because it seems useless for now, as any testing of these kexts won’t yield any different result than on our side, and people might get confused and start making issues about how the builds don’t work
